version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /Proyects/cmd/testing1:/go/src/app
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"

