// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: proto/grpc_cache.proto

package grpc_cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFromCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetFromCacheRequest) Reset() {
	*x = GetFromCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpc_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromCacheRequest) ProtoMessage() {}

func (x *GetFromCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromCacheRequest.ProtoReflect.Descriptor instead.
func (*GetFromCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetFromCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetFromCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetFromCacheResponse) Reset() {
	*x = GetFromCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpc_cache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromCacheResponse) ProtoMessage() {}

func (x *GetFromCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_cache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromCacheResponse.ProtoReflect.Descriptor instead.
func (*GetFromCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetFromCacheResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetInCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetInCacheRequest) Reset() {
	*x = SetInCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpc_cache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetInCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInCacheRequest) ProtoMessage() {}

func (x *SetInCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_cache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInCacheRequest.ProtoReflect.Descriptor instead.
func (*SetInCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_cache_proto_rawDescGZIP(), []int{2}
}

func (x *SetInCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetInCacheRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetInCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SetInCacheResponse) Reset() {
	*x = SetInCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpc_cache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetInCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInCacheResponse) ProtoMessage() {}

func (x *SetInCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_cache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInCacheResponse.ProtoReflect.Descriptor instead.
func (*SetInCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_cache_proto_rawDescGZIP(), []int{3}
}

func (x *SetInCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFromDatabaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetFromDatabaseRequest) Reset() {
	*x = GetFromDatabaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpc_cache_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromDatabaseRequest) ProtoMessage() {}

func (x *GetFromDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_cache_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromDatabaseRequest.ProtoReflect.Descriptor instead.
func (*GetFromDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_grpc_cache_proto_rawDescGZIP(), []int{4}
}

func (x *GetFromDatabaseRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetFromDatabaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetFromDatabaseResponse) Reset() {
	*x = GetFromDatabaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_grpc_cache_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFromDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFromDatabaseResponse) ProtoMessage() {}

func (x *GetFromDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grpc_cache_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFromDatabaseResponse.ProtoReflect.Descriptor instead.
func (*GetFromDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_grpc_cache_proto_rawDescGZIP(), []int{5}
}

func (x *GetFromDatabaseResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_grpc_cache_proto protoreflect.FileDescriptor

var file_proto_grpc_cache_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2c, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x53,
	0x65, 0x74, 0x49, 0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x49,
	0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x2f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xb2, 0x01, 0x0a, 0x0c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0a, 0x53,
	0x65, 0x74, 0x49, 0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x6f, 0x0a, 0x0f, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x12, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_grpc_cache_proto_rawDescOnce sync.Once
	file_proto_grpc_cache_proto_rawDescData = file_proto_grpc_cache_proto_rawDesc
)

func file_proto_grpc_cache_proto_rawDescGZIP() []byte {
	file_proto_grpc_cache_proto_rawDescOnce.Do(func() {
		file_proto_grpc_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_grpc_cache_proto_rawDescData)
	})
	return file_proto_grpc_cache_proto_rawDescData
}

var file_proto_grpc_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_grpc_cache_proto_goTypes = []interface{}{
	(*GetFromCacheRequest)(nil),     // 0: grpc_cache.GetFromCacheRequest
	(*GetFromCacheResponse)(nil),    // 1: grpc_cache.GetFromCacheResponse
	(*SetInCacheRequest)(nil),       // 2: grpc_cache.SetInCacheRequest
	(*SetInCacheResponse)(nil),      // 3: grpc_cache.SetInCacheResponse
	(*GetFromDatabaseRequest)(nil),  // 4: grpc_cache.GetFromDatabaseRequest
	(*GetFromDatabaseResponse)(nil), // 5: grpc_cache.GetFromDatabaseResponse
}
var file_proto_grpc_cache_proto_depIdxs = []int32{
	0, // 0: grpc_cache.CacheService.GetFromCache:input_type -> grpc_cache.GetFromCacheRequest
	2, // 1: grpc_cache.CacheService.SetInCache:input_type -> grpc_cache.SetInCacheRequest
	4, // 2: grpc_cache.DatabaseService.GetFromDatabase:input_type -> grpc_cache.GetFromDatabaseRequest
	1, // 3: grpc_cache.CacheService.GetFromCache:output_type -> grpc_cache.GetFromCacheResponse
	3, // 4: grpc_cache.CacheService.SetInCache:output_type -> grpc_cache.SetInCacheResponse
	5, // 5: grpc_cache.DatabaseService.GetFromDatabase:output_type -> grpc_cache.GetFromDatabaseResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grpc_cache_proto_init() }
func file_proto_grpc_cache_proto_init() {
	if File_proto_grpc_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_grpc_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpc_cache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpc_cache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetInCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpc_cache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetInCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpc_cache_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromDatabaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_grpc_cache_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFromDatabaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_grpc_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_grpc_cache_proto_goTypes,
		DependencyIndexes: file_proto_grpc_cache_proto_depIdxs,
		MessageInfos:      file_proto_grpc_cache_proto_msgTypes,
	}.Build()
	File_proto_grpc_cache_proto = out.File
	file_proto_grpc_cache_proto_rawDesc = nil
	file_proto_grpc_cache_proto_goTypes = nil
	file_proto_grpc_cache_proto_depIdxs = nil
}
