version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /Proyects/cmd/testing1:/app
    depends_on:
      - redis
      - mysql

  redis:
    image: redis
    ports:
      - "6379:6379"
